# Service object for the kubelet running on master node.
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: master
  labels:
    k8s-app: master
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: etcd-2379
      port: 2379
    - name: etcd-2382
      port: 2382
    - name: kubelet
      port: 10250
    - name: node-exporter
      port: 9100
