# Endpoints object for the kubelet running on master node.
apiVersion: v1
kind: Endpoints
metadata:
  namespace: kube-system
  name: master
  labels:
    k8s-app: master
subsets:
  - addresses:
    {{range .MasterIps}}
      - ip: {{.}}
    {{end}}
    ports:
      - name: etcd-2379
        port: 2379
      - name: etcd-2382
        port: 2382
      - name: kubelet
        port: 10250
      - name: node-exporter
        port: 9100
